apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8teste-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8teste
  template:
    metadata:
      labels:
        app: k8teste
    spec:
      containers:
        - name: k8teste-container
          image: k8teste
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
